# Generated by Django 4.1.7 on 2023-03-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEVICES',
            fields=[
                ('IPAdress', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=500)),
                ('DateLogin', models.DateField()),
                ('DeviceType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PROFILE',
            fields=[
                ('UserName', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=500)),
            ],
        ),
    ]
